### ISSUE TITLE
Create marketplace entry for tWAS Base single server

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.websphere-traditional.singleserver#12]
This issue is to ask for creating an Azure application offer which contains the solution of deploying a tWAS Base single server on Azure.

**Comment by edburns** [comment]
@git4rk  please assign this to me.

**Comment by edburns** [comment]
| Offer Alias | Offer ID |
|-------------|----------|
| 2022-01-07-twas-base-single-server | 2022-01-07-twas-base-single-server |

**Comment by edburns** [comment]
@git4rk  please close this issue.

**Comment by majguo** [comment]
Hello @edburns , could you pls also share the tracking pid of the plan here? Thanks.

**Comment by majguo** [comment]
Hello @edburns , I'd like to keep this issue open until the tWAS single server application offer you created is live and can be accessed by external users. What do you think?

**Comment by majguo** [comment]
Close the issue as the application offer is live now.
