### ISSUE TITLE
Create a license link for tWAS Base single server offer

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.websphere-traditional.singleserver#13]
In the UI of tWAS ND cluster offer, there is a license link:
- text: IBM WebSphere Application Server Network Deployment
- url: https://ibm.biz/tWASNDLicenseAzureVMs

The issue is to request a similar license link for tWAS Base single server offer:
- text: ?
- url: ?

**Comment by majguo** [comment]
Hello @git4rk , could you pls help on it? Thanks.

**Comment by git4rk** [comment]
@majguo Please use:
text: IBM WebSphere Application Server
URL: https://ibm.biz/tWASBaseLicenseAzureVMs
