### ISSUE TITLE
Issues with Marketplace entry

### ISSUE THREAD

**Issue by git4rk** [WASdev/azure.websphere-traditional.singleserver#18]
1. Provider name is different than other offerings
![image](https://user-images.githubusercontent.com/24283162/150346330-a0a8feed-ccfb-43d3-824b-6171349c6597.png)
If we have option to set the provider name then all offers should be updated to set a meaningful name, probably `IBM`, instead of `IBM-USA-NY-Armonk-HQ-6275750-IBMCloud-AIOps`
2. Remove current video. It is for the cluster offering. Another issue is opened to create single server video: #17. Remove this video from Portal also.
3. Plan names look different than Cluster offering: `cluster` vs `2022-01-07-twas-base-single-server`
![image](https://user-images.githubusercontent.com/24283162/150347642-ae85f560-4abe-4d18-b6d4-9762d65573c2.png)

   ![image](https://user-images.githubusercontent.com/24283162/150347748-10876596-42e7-45f3-9833-7d57bc6bacac.png)

4. This should be "Virtual Machine"
![image](https://user-images.githubusercontent.com/24283162/150348060-c84ab056-563f-4812-963c-65051e2f64be.png)

**Comment by gcharters** [comment]
I've updated the icons and fixed the "on Virtual Machines".  I've also done some other tidy-up items for improved consistency, e.g. Traditional to traditional because it's not part of the product name.

I've so far been unable to find where "Websphere" is set for the publisher.

**Comment by gcharters** [comment]
I have found a contact who I believe can request the change to the Publisher Name.  I have requested it be changed to `IBM WebSphere`.

**Comment by git4rk** [comment]
1. Done

![image](https://user-images.githubusercontent.com/24283162/152043846-b2512507-b55e-4735-bd57-bd3fff38dbf1.png)

3. Done
![image](https://user-images.githubusercontent.com/24283162/152043962-4659e340-4d4c-47f6-a1e0-6fd9743659cc.png)
![image](https://user-images.githubusercontent.com/24283162/152043997-8a963f2c-dc28-4258-a396-7da9d7f9ba72.png)

4. Done
![image](https://user-images.githubusercontent.com/24283162/152044170-58e9b3c8-ad8d-4471-bab9-8bf05c6e9f12.png)

**Comment by git4rk** [comment]
Closing since all items have been addressed.
