### ISSUE TITLE
Create marketplace entry for base image of tWAS Base edition trial

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.websphere-traditional.singleserver#3]

**Comment by majguo** [comment]
Hello @git4rk Could you pls assign it to @edburns? Thanks.

**Comment by edburns** [comment]
I am interpreting this issue to mean that I must create a base image for tWAS base edition single server trial, in contrast to the non-trial of the same, as requested in #6.

**Comment by edburns** [comment]
| Offer Alias|Offer ID|
|------------|---------|
|2022-01-06-twas-base-single-server-trial | 2022-01-06-twas-base-single-server-trial|

**Comment by edburns** [comment]
@git4rk  please close this issue.

**Comment by git4rk** [comment]
@majguo @edburns I thought this issue was to create marketplace entry for the entitled version of tWAS Base image, and #6 was to create marketplace entry for the tWAS Base solution.

BTW, have we considered using the same solution catalog entry for Cluster and Base?

**Comment by edburns** [comment]
@git4rk  wrote:

> BTW, have we considered using the same solution catalog entry for Cluster and Base?

We had not considered it until your suggestion.  However, after consideration, I judge it is best to continue to have two separate Azure Application offers, one for Cluster and one for Single Server.  Here are some justifications for this approach:
- The UI elements, such as tabs and labels, are more clear when we can tailor them to the specific scenario.  For example, "Server configuration" vs. "Cluster configuration".
- The cluster offer is planned to have additional tabs that will never apply to the single server case, for example App Gateway and perhaps others later.

**Comment by majguo** [comment]
> @majguo @edburns I thought this issue was to create marketplace entry for the entitled version of tWAS Base image, and #6 was to create marketplace entry for the tWAS Base solution.

@git4rk Yes, you're right. To match what @edburns have created, I updated titles for both issue #3 and #6 accordingly so they won't create confusion.

Besides, I created a new issue #12 for tracking the purpose of creating marketplace entry for the tWAS Base solution.

**Comment by majguo** [comment]
Hello @edburns , I'd like to keep this issue open until the offer you created can be referenced in the tWAS single server offer as a workable image. What do you think?

**Comment by majguo** [comment]
Based on the latest decision, the same twas base image will be used for both entitlement and evaluation editions, so this issue is no longer valid, closing the issue now.
