### ISSUE TITLE
Create GitHub Action secrets needed to run new added pipeline `integration-test`

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.websphere-traditional.singleserver#44]
Hello @git4rk The following GitHub Action secrets are needed to run new added pipeline `integration-test`

* AZURE_CREDENTIALS
  * Use the same value of secret `AZURE_CREDENTIALS` defined in [WASdev/azure.websphere-traditional.image](https://github.com/WASdev/azure.websphere-traditional.image)
* USER_NAME
  * Use `WASdev`
* VM_ADMIN_ID
  * The username used for the VM and websphere console, pls define by yourself
* VM_ADMIN_PASSWORD
  * The password used for the VM and websphere console, pls define by yourself
* MSTEAMS_WEBHOOK
  * Use the same value of secret `MSTEAMS_WEBHOOK` defined in [WASdev/azure.websphere-traditional.image](https://github.com/WASdev/azure.websphere-traditional.image)

Reference the following related issues if you need more background information
* WASdev/azure.websphere-traditional.cluster/issues/153
* WASdev/azure.websphere-traditional.cluster/issues/58

**Comment by git4rk** [comment]
Added secrets to https://github.com/WASdev/azure.websphere-traditional.singleserver/settings/secrets/actions
<img width="854" alt="image" src="https://user-images.githubusercontent.com/24283162/188016560-0b7ec5d1-aa50-418e-98dd-922edffbf77b.png">

**Comment by majguo** [comment]
Hello @git4rk Pls close the issue as you already added required secrets.
