### ISSUE TITLE
Create GitHub Action secret needed to enable Oracle database connection in the existing `integration-test` pipeline

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.websphere-traditional.singleserver#56]
Hello @git4rk The following **additional** GitHub Action secret is needed to **enable Oracle database connection** in the existing pipeline `integration-test`:

* ORACLE_DB_PASSWORD
  *  Specify the password for testing account (`testuser`) of Oracle database server.

Reference the following issue for the other GitHub Action secrets required for pipeline `integration-test`:
* #47
* #44

**Comment by majguo** [comment]
Hello @git4rk Pls close the issue once you add the required secret.

**Comment by git4rk** [comment]
secret created
