### ISSUE TITLE
Create marketplace entry for base image of tWAS Base edition

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.websphere-traditional.singleserver#6]

**Comment by majguo** [comment]
Hello @git4rk Could you pls assign it to @edburns? Thanks.

**Comment by edburns** [comment]
Created

| Offer Alias|Offer ID|
|------------|---------|
|2022-01-06-twas-single-server-base-image | 2022-01-06-twas-base-single-server|

**Comment by edburns** [comment]
@git4rk  Please close this issue.

**Comment by majguo** [comment]
Hello @edburns , I'd like to keep this issue open until the offer you created can be referenced in the tWAS single server offer as a workable image. What do you think?

**Comment by majguo** [comment]
The `urn` of the vm image is: `ibm-alliance-usa-ny-armonk-hq-ibmstorage-6201192:ibm-svpc-azure-843-base-vm:svpc-8430-211209-2206:843.0.2112092206`, closing the ticket now.
