### ISSUE TITLE
Review the labels, description/help, default values, etc. from UI

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.websphere-traditional.singleserver#8]
## Overview

The UI of tWAS single server offer origins from the UI of **GAed** [tWAS cluster offer](https://ms.portal.azure.com/#create/ibm-usa-ny-armonk-hq-6275750-ibmcloud-aiops.2021-04-08-twas-clustercluster). To simplify the review, the following comparison details is summarized:
* Tab **Basic**: exactly same
   * Screenshot (text in the box):
     ![image](https://user-images.githubusercontent.com/10357495/147323798-04e9203b-10f8-431a-ac1f-9266b0add43c.png)
 
* Tab **Server configuration** vs tab **Cluster configuration**
   * Tab name is changed from **Cluster** configuration to **Server** configuration
   * Section **Number of VMs** is removed
   * Section **Deployment manager server prefix** is removed
   * Section **Managed server prefix** is removed
   * Section **DNS label prefix** is changed
      * Default value and tooltip are changed from **wasndcluster** to **was**
   * Screenshot:
      ![image](https://user-images.githubusercontent.com/10357495/147323252-9716dc41-09a1-4a9b-8cbc-d94fd979f544.png)
* Tab **IBM HTTP Server Load Balancer** is removed 

## How to preview the UI

To facilitate the review, reviewers can preview the changes using the **Create UI Definition Sandbox**:
- Open [Create UI Definition Sandbox](https://portal.azure.com/?feature.customPortal=false#blade/Microsoft_Azure_CreateUIDef/SandboxBlade) in a new tab of browser;
- Download the source code  [createUiDefinition.json.txt](https://github.com/WASdev/azure.websphere-traditional.singleserver/files/7772838/createUiDefinition.json.txt) and open it in a text editor;
- Replace the content of work area in **Create UI Definition Sandbox** with the content of **source code `createUiDefinition.json.txt`**;
- Click **Preview** at the left-bottom of **Create UI Definition Sandbox**;

**Comment by majguo** [comment]
Hello @helyarp @git4rk , could you pls help review the content for tWAS single server offer? Thanks.

**Comment by edburns** [comment]
Can we consider adding a Yes/No option to provide a public IP address for the single server?  Default to Yes.

**Comment by majguo** [comment]
Thanks @edburns for your comment. @gcharters @m-reza-rahman , feel free to review the UI design of single server by following steps in "How to preview the UI".

**Comment by git4rk** [comment]
@majguo I reviewed the text and they look good to me.

**Comment by helyarp** [comment]
@majguo Hi, I like the UI changes. I have a few suggested changes:

## Basics tab

- Change **IBM ID** to **IBMid**. (Cutomers who get an IBM account, get an IBMid. https://www.ibm.com/account)
- Change  **please report them here**  to  **open an issue**  or  **open an Azure issue**.
- Change  **file an issue**  to  **open an issue**

**Question:** Why are the links below the sentences and not part of the sentences?

## Server configuration tab

No needed changes. **VM** is acceptable but, if Microsoft typically spells out acronyms, use **virtual machine** instead.

**Comment by majguo** [comment]
Thanks @helyarp for your review and suggested changes. The original text came from @gcharters & @edburns. Hello Graham & Ed, could you pls take a look at Pam's suggestions above and share your feedback? Thanks.

**Comment by gcharters** [comment]
> @majguo Hi, I like the UI changes. I have a few suggested changes:
> 
> ## Basics tab
> * Change **IBM ID** to **IBMid**. (Cutomers who get an IBM account, get an IBMid. https://www.ibm.com/account)
> * Change  **please report them here**  to  **open an issue**  or  **open an Azure issue**.
> * Change  **file an issue**  to  **open an issue**
> 
> **Question:** Why are the links below the sentences and not part of the sentences?
> 
> ## Server configuration tab
> No needed changes. **VM** is acceptable but, if Microsoft typically spells out acronyms, use **virtual machine** instead.

Hi @helyarp , thanks for the feedback.  For the IBMid change, can you confirm that this is how it should be officially referenced?  When we investigated previously, there seemed to be no consistency so we just went with IBM ID which seemed to be used on a few official sites.

For the other changes, is the intent that the new suggested text be hyperlinks, or when they still then be followed by the links to the sites?  E.g. To use your existing IBM support contact, [open an issue](https://linktoibmsupportpage) with IBM directly.

**Comment by helyarp** [comment]
@gcharters The [IBM Multilingual Terminology database](https://w3.ibm.com/standards/terminology/cgi-bin/lookup.pl?user_group=corporate) says to use IBMid. The database is IBM internal and lists the accepted terms for IBM doc, products, communication, etc. The IBMid and IBM ID definitions in the database are--

## IBMid

noun

    An ID that is used to access external IBM products and services.

    _Usage note:_ Write as shown--one word, to refer to the user ID for ibm.com.

    **Comment:** **IBMid has replaced IBM ID as the preferred form for the SSO process. IBMid is now the untranslated preferred form for all languages.** [bold added]
    
## IBM ID

noun

    See: IBMid.

    _Approval status_: Do not use.
    _Usage note:_ Use "IBMid."

**Comment by edburns** [comment]
@helyarp wrote:

> Question: Why are the links below the sentences and not part of the sentences?

Answer: this is a limitation of the declarative UI element of the portal.  See [the Microsoft documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/microsoft-common-textblock?WT.mc_id=Portal-Microsoft_Azure_CreateUIDef).

**Comment by edburns** [comment]
I have filed a cross-repo issue.  Please see https://github.com/WASdev/azure.websphere-traditional.cluster/issues/135 .

**Comment by majguo** [comment]
Thank you all @helyarp @gcharters @edburns . Per all of your inputs, I'd like to make the following changes:

Basics tab
----------------
* Change **IBM ID** to **IBMid**. This change will be applied to all occurrences including template and scripts.
* Change **please report them here** to **open an issue**.
* Change **file an issue** to **open an issue**

Besides, I'll also open another PR to apply the above changes to the tWAS cluster offer. I'll share PR links here once they're available.

**Comment by majguo** [comment]
Hello @helyarp Would you pls also help review the similar text changes in the other two PRs listed below? Thanks.
* https://github.com/WASdev/azure.liberty.aro/pull/51
* https://github.com/WASdev/azure.liberty.aks/pull/24
